version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:8000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
  db:
    image: postgres
    environment:
      - POSTGRES_DB=development_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    ports:
      - "5432:5432"
