version: '3.8'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=8000
    volumes:
      - .:/app
    ports:
      - "146.59.3.224:5000:8000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=development_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    ports:
      - "146.59.3.224:5432:5432"
